#
# This file has been customized after generated by
# the "pkg_mkIndex" command. 
#
package ifneeded LIBWACOMXI 1.0 [list tclPkgSetup $dir LIBWACOMXI 1.0 {{libwacomxi.so load {wacomxi::bindevent }}}]
