/* src/include/util-config.h.  Generated by configure.  */
/* util-config.h.in */

#ifndef _UTIL_CONFIG_H_
#define _UTIL_CONFIG_H_

/* ncurses header files available */
#define WCM_ENABLE_NCURSES 1

/* Enable the Linux Input subsystem */
#define WCM_ENABLE_LINUXINPUT 

#endif /* _UTIL_CONFIG_H_ */
