/* src/include/xdrv-config.h.  Generated by configure.  */
/* xdrv-config.h.in */

#ifndef _XDRV_CONFIG_H_
#define _XDRV_CONFIG_H_

/* Misc defines moved from the command line */
#define AVOID_GLYPHBLT 
#define _BSD_SOURCE 
#define BUILDDEBUG 
#define DPMSExtension 
#define FUNCPROTO 15
#define GCCUSESGAS 
#define _GNU_SOURCE 
#define IN_MODULE 
#define LBX 
#define linux 
#define NARROWPROTO 
#define NDEBUG 
#define PIXPRIV 
#define _POSIX_C_SOURCE 
#define _POSIX_SOURCE 
#define RENDER 
#define SHAPE 
#define SINGLEDEPTH 
#define SMART_SCHEDULE 
#define _SVID_SOURCE 
#define TOGCUP 
#define XAPPGROUP 
#define X_BYTE_ORDER X_LITTLE_ENDIAN
#define XCSECURITY 
#define XF86BIGFONT 
#define XF86VIDMODE 
#define XFree86LOADER 
#define XFree86Module 
#define XFree86Server 
#define XFreeXDGA 
#define XINPUT 
#define XKB 
#define _XOPEN_SOURCE 
#define XResExtension 
#define XvExtension 
#define XvMCExtension 

/* Compiling for X.org */
#define WCM_XORG 1

/* Compiling for XFree86 */
/* #undef WCM_XFREE86 */

/* Enable the Linux Input subsystem */
#define WCM_ENABLE_LINUXINPUT 

/* The xserver have no wraps around libc-functions */
/* #undef WCM_NO_LIBCWRAPPER */

#endif /* _XDRV_CONFIG_H_ */
